-- AddColumn shift breakdown and tcsAmount to RevenueEntry
ALTER TABLE "RevenueEntry"
  ADD COLUMN "shift1Cash"    DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift1Pix"     DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift1Card"    DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift1Ticket"  DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift1Service" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift1Tcs"     DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Cash"    DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Pix"     DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Card"    DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Ticket"  DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Service" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "shift2Tcs"     DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "tcsAmount"     DECIMAL(14,2) NOT NULL DEFAULT 0;
