ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'INTERNAL_CONSUMPTION';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'EMPLOYEE_PURCHASE';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'POSITIVE_ADJUSTMENT';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'NEGATIVE_ADJUSTMENT';
ALTER TYPE "InventoryMovementType" ADD VALUE IF NOT EXISTS 'RETURN';
