CREATE TYPE "IfoodMonthlyExpenseStatus" AS ENUM ('OPEN', 'PARTIALLY_PAID', 'PAID', 'CANCELLED');

CREATE TABLE "IfoodMonthlyExpense" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT NOT NULL,
    "companyId" TEXT,
    "competenceYear" INTEGER NOT NULL,
    "competenceMonth" INTEGER NOT NULL,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "commissionAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "deliveryFeeAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "marketingAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "maintenanceAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "anticipationAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "otherAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "totalAmount" DECIMAL(14,2) NOT NULL,
    "paidAmount" DECIMAL(14,2),
    "status" "IfoodMonthlyExpenseStatus" NOT NULL DEFAULT 'OPEN',
    "paidAt" TIMESTAMP(3),
    "paymentMethod" TEXT,
    "notes" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "cancelledAt" TIMESTAMP(3),
    "cancellationReason" TEXT,

    CONSTRAINT "IfoodMonthlyExpense_pkey" PRIMARY KEY ("id")
);

-- Nomes de índice curtos: Postgres tem limite de 63 chars e o padrão do Prisma passava disso.
CREATE UNIQUE INDEX "ifme_store_competence_uniq" ON "IfoodMonthlyExpense"("deliveryStoreId", "competenceYear", "competenceMonth");
CREATE INDEX "ifme_status_due_idx" ON "IfoodMonthlyExpense"("status", "dueDate");
CREATE INDEX "ifme_company_competence_idx" ON "IfoodMonthlyExpense"("companyId", "competenceYear", "competenceMonth");

ALTER TABLE "IfoodMonthlyExpense" ADD CONSTRAINT "IfoodMonthlyExpense_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IfoodMonthlyExpense" ADD CONSTRAINT "IfoodMonthlyExpense_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
