-- AlterEnum
ALTER TYPE "VtCommute" ADD VALUE 'BILHETE_MENSAL_ONIBUS';
ALTER TYPE "VtCommute" ADD VALUE 'BILHETE_MENSAL_INTEGRADO';

-- AlterTable
ALTER TABLE "PayrollSettings" ADD COLUMN     "monthlyPassBus" DECIMAL(8,2) NOT NULL DEFAULT 257.53,
ADD COLUMN     "monthlyPassIntegrated" DECIMAL(8,2) NOT NULL DEFAULT 411.13;
