-- Integração 99 Food — espelha padrão iFood.
-- Enum DeliveryPlatform.NOVENTA_NOVE já existe desde a migration
-- 20260709120000_add_delivery_ifood_integration, então tabelas
-- transacionais 99 Food usam a DeliveryStore existente via FK.

-- CreateTable NoventaNoveCredential
CREATE TABLE "NoventaNoveCredential" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "clientSecret" TEXT NOT NULL,
    "environment" TEXT NOT NULL DEFAULT 'PRODUCTION',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastTokenAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NoventaNoveCredential_pkey" PRIMARY KEY ("id")
);

-- CreateTable NoventaNoveSale
CREATE TABLE "NoventaNoveSale" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT NOT NULL,
    "externalOrderId" TEXT NOT NULL,
    "orderDate" TIMESTAMP(3) NOT NULL,
    "competenceYear" INTEGER NOT NULL,
    "competenceMonth" INTEGER NOT NULL,
    "grossAmount" DECIMAL(14,2) NOT NULL,
    "noventaNoveFeeAmount" DECIMAL(14,2) NOT NULL,
    "promotionAmount" DECIMAL(14,2) NOT NULL,
    "deliveryFeeAmount" DECIMAL(14,2) NOT NULL,
    "netAmount" DECIMAL(14,2) NOT NULL,
    "paymentMethod" TEXT,
    "channel" TEXT,
    "rawPayload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NoventaNoveSale_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "nnsale_store_order_uniq" ON "NoventaNoveSale"("deliveryStoreId", "externalOrderId");
CREATE INDEX "nnsale_store_competence_idx" ON "NoventaNoveSale"("deliveryStoreId", "competenceYear", "competenceMonth");
CREATE INDEX "nnsale_store_orderdate_idx" ON "NoventaNoveSale"("deliveryStoreId", "orderDate");

-- CreateTable NoventaNoveSettlement
CREATE TABLE "NoventaNoveSettlement" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "periodStart" TIMESTAMP(3) NOT NULL,
    "periodEnd" TIMESTAMP(3) NOT NULL,
    "grossAmount" DECIMAL(14,2) NOT NULL,
    "totalFees" DECIMAL(14,2) NOT NULL,
    "netAmount" DECIMAL(14,2) NOT NULL,
    "paidAt" TIMESTAMP(3),
    "status" TEXT NOT NULL,
    "rawPayload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NoventaNoveSettlement_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "nnstl_store_external_uniq" ON "NoventaNoveSettlement"("deliveryStoreId", "externalId");
CREATE INDEX "nnstl_store_period_idx" ON "NoventaNoveSettlement"("deliveryStoreId", "periodStart");

-- CreateTable NoventaNoveFee
CREATE TABLE "NoventaNoveFee" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT NOT NULL,
    "competenceYear" INTEGER NOT NULL,
    "competenceMonth" INTEGER NOT NULL,
    "feeType" TEXT NOT NULL,
    "description" TEXT,
    "amount" DECIMAL(14,2) NOT NULL,
    "rawPayload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NoventaNoveFee_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "nnfee_store_competence_idx" ON "NoventaNoveFee"("deliveryStoreId", "competenceYear", "competenceMonth");
CREATE INDEX "nnfee_store_type_idx" ON "NoventaNoveFee"("deliveryStoreId", "feeType");

-- CreateTable NoventaNoveSyncLog
CREATE TABLE "NoventaNoveSyncLog" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT,
    "syncType" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "finishedAt" TIMESTAMP(3),
    "status" TEXT NOT NULL,
    "itemsProcessed" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "triggeredByUserId" TEXT,

    CONSTRAINT "NoventaNoveSyncLog_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "nnlog_store_started_idx" ON "NoventaNoveSyncLog"("deliveryStoreId", "startedAt");

-- CreateEnum + Table NoventaNoveMonthlyExpense
CREATE TYPE "NoventaNoveMonthlyExpenseStatus" AS ENUM ('OPEN', 'PARTIALLY_PAID', 'PAID', 'CANCELLED');

CREATE TABLE "NoventaNoveMonthlyExpense" (
    "id" TEXT NOT NULL,
    "deliveryStoreId" TEXT NOT NULL,
    "companyId" TEXT,
    "competenceYear" INTEGER NOT NULL,
    "competenceMonth" INTEGER NOT NULL,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "commissionAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "deliveryFeeAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "marketingAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "maintenanceAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "anticipationAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "otherAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "totalAmount" DECIMAL(14,2) NOT NULL,
    "paidAmount" DECIMAL(14,2),
    "status" "NoventaNoveMonthlyExpenseStatus" NOT NULL DEFAULT 'OPEN',
    "paidAt" TIMESTAMP(3),
    "paymentMethod" TEXT,
    "notes" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "cancelledAt" TIMESTAMP(3),
    "cancellationReason" TEXT,

    CONSTRAINT "NoventaNoveMonthlyExpense_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "nnme_store_competence_uniq" ON "NoventaNoveMonthlyExpense"("deliveryStoreId", "competenceYear", "competenceMonth");
CREATE INDEX "nnme_status_due_idx" ON "NoventaNoveMonthlyExpense"("status", "dueDate");
CREATE INDEX "nnme_company_competence_idx" ON "NoventaNoveMonthlyExpense"("companyId", "competenceYear", "competenceMonth");

-- Receivable — nova FK opcional para settlements 99 Food
ALTER TABLE "Receivable" ADD COLUMN "noventaNoveSettlementId" TEXT;
CREATE UNIQUE INDEX "Receivable_noventaNoveSettlementId_key" ON "Receivable"("noventaNoveSettlementId");

-- Foreign Keys
ALTER TABLE "NoventaNoveSale" ADD CONSTRAINT "NoventaNoveSale_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NoventaNoveSettlement" ADD CONSTRAINT "NoventaNoveSettlement_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NoventaNoveFee" ADD CONSTRAINT "NoventaNoveFee_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NoventaNoveSyncLog" ADD CONSTRAINT "NoventaNoveSyncLog_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NoventaNoveMonthlyExpense" ADD CONSTRAINT "NoventaNoveMonthlyExpense_deliveryStoreId_fkey" FOREIGN KEY ("deliveryStoreId") REFERENCES "DeliveryStore"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NoventaNoveMonthlyExpense" ADD CONSTRAINT "NoventaNoveMonthlyExpense_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Receivable" ADD CONSTRAINT "Receivable_noventaNoveSettlementId_fkey" FOREIGN KEY ("noventaNoveSettlementId") REFERENCES "NoventaNoveSettlement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
