import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../config/database.js";
import { requireRole } from "../security/security-utils.js";

export const ifoodExpenseRouter = Router();

const READ_ROLES = ["ADMIN", "GESTAO_COMPLETA", "VISUALIZACAO"] as const;
const WRITE_ROLES = ["ADMIN", "GESTAO_COMPLETA"] as const;

const listQuery = z.object({
  status: z.enum(["OPEN", "PARTIALLY_PAID", "PAID", "CANCELLED"]).optional(),
  companyId: z.string().trim().optional(),
  competenceYear: z.coerce.number().int().optional(),
  competenceMonth: z.coerce.number().int().optional()
});

const payInput = z.object({
  paidAt: z.string().trim().min(8, "data obrigatória"),
  paidAmount: z.coerce.number().nonnegative(),
  paymentMethod: z.string().trim().optional().nullable(),
  notes: z.string().trim().optional().nullable()
});

function toNumber(v: unknown): number {
  if (v === null || v === undefined) return 0;
  if (typeof v === "number") return v;
  return Number(String(v)) || 0;
}

function toView(row: {
  id: string;
  deliveryStoreId: string;
  deliveryStore: { nickname: string };
  companyId: string | null;
  company: { tradeName: string } | null;
  competenceYear: number;
  competenceMonth: number;
  dueDate: Date;
  commissionAmount: unknown;
  deliveryFeeAmount: unknown;
  marketingAmount: unknown;
  maintenanceAmount: unknown;
  anticipationAmount: unknown;
  otherAmount: unknown;
  totalAmount: unknown;
  paidAmount: unknown;
  status: string;
  paidAt: Date | null;
  paymentMethod: string | null;
  notes: string | null;
  autoGenerated: boolean;
  createdAt: Date;
}) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const due = new Date(row.dueDate);
  due.setHours(0, 0, 0, 0);
  const daysUntilDue = Math.round((due.getTime() - today.getTime()) / (86400000));
  const isLate = row.status === "OPEN" && daysUntilDue < 0;
  return {
    id: row.id,
    deliveryStoreId: row.deliveryStoreId,
    storeNickname: row.deliveryStore.nickname,
    companyId: row.companyId,
    companyName: row.company?.tradeName ?? null,
    competenceYear: row.competenceYear,
    competenceMonth: row.competenceMonth,
    dueDate: row.dueDate.toISOString().slice(0, 10),
    commissionAmount: toNumber(row.commissionAmount),
    deliveryFeeAmount: toNumber(row.deliveryFeeAmount),
    marketingAmount: toNumber(row.marketingAmount),
    maintenanceAmount: toNumber(row.maintenanceAmount),
    anticipationAmount: toNumber(row.anticipationAmount),
    otherAmount: toNumber(row.otherAmount),
    totalAmount: toNumber(row.totalAmount),
    paidAmount: row.paidAmount === null ? null : toNumber(row.paidAmount),
    status: row.status,
    paidAt: row.paidAt ? row.paidAt.toISOString().slice(0, 10) : null,
    paymentMethod: row.paymentMethod,
    notes: row.notes,
    autoGenerated: row.autoGenerated,
    daysUntilDue,
    isLate,
    createdAt: row.createdAt.toISOString()
  };
}

ifoodExpenseRouter.get("/", async (request, response) => {
  const user = await requireRole(request, response, [...READ_ROLES]);
  if (!user) return;
  const parsed = listQuery.safeParse(request.query);
  if (!parsed.success) {
    response.status(400).json({ message: "Parâmetros inválidos", errors: parsed.error.flatten() });
    return;
  }
  const where: Record<string, unknown> = {};
  if (parsed.data.status) where.status = parsed.data.status;
  if (parsed.data.companyId) where.companyId = parsed.data.companyId;
  if (parsed.data.competenceYear) where.competenceYear = parsed.data.competenceYear;
  if (parsed.data.competenceMonth) where.competenceMonth = parsed.data.competenceMonth;

  const rows = await prisma.ifoodMonthlyExpense.findMany({
    where,
    include: {
      deliveryStore: { select: { nickname: true } },
      company: { select: { tradeName: true } }
    },
    orderBy: [{ competenceYear: "desc" }, { competenceMonth: "desc" }, { deliveryStoreId: "asc" }]
  });
  response.json(rows.map(toView));
});

ifoodExpenseRouter.post("/:id/pay", async (request, response) => {
  const user = await requireRole(request, response, [...WRITE_ROLES]);
  if (!user) return;
  const parsed = payInput.safeParse(request.body);
  if (!parsed.success) {
    response.status(400).json({ message: "Payload inválido", errors: parsed.error.flatten() });
    return;
  }
  const existing = await prisma.ifoodMonthlyExpense.findUnique({ where: { id: request.params.id } });
  if (!existing) {
    response.status(404).json({ message: "Despesa não encontrada" });
    return;
  }
  const total = toNumber(existing.totalAmount);
  const status = parsed.data.paidAmount >= total - 0.005 ? "PAID" : "PARTIALLY_PAID";
  const updated = await prisma.ifoodMonthlyExpense.update({
    where: { id: existing.id },
    data: {
      status,
      paidAt: new Date(parsed.data.paidAt),
      paidAmount: parsed.data.paidAmount,
      paymentMethod: parsed.data.paymentMethod ?? existing.paymentMethod,
      notes: parsed.data.notes ?? existing.notes
    },
    include: {
      deliveryStore: { select: { nickname: true } },
      company: { select: { tradeName: true } }
    }
  });
  response.json(toView(updated));
});

ifoodExpenseRouter.post("/:id/cancel", async (request, response) => {
  const user = await requireRole(request, response, [...WRITE_ROLES]);
  if (!user) return;
  const reason = typeof request.body?.reason === "string" ? request.body.reason : null;
  const updated = await prisma.ifoodMonthlyExpense.update({
    where: { id: request.params.id },
    data: {
      status: "CANCELLED",
      cancelledAt: new Date(),
      cancellationReason: reason
    },
    include: {
      deliveryStore: { select: { nickname: true } },
      company: { select: { tradeName: true } }
    }
  });
  response.json(toView(updated));
});
